// src/lib/creatorStudio.js
// ── Creator Studio — cinematic teaser project data ──────────────
// Reverse-engineered in-house equivalent of the Opus.pro "Creator
// Studio" concept (anchors / locations / vehicles & gear) built on
// the ElevenLabs creative pipeline (Nano Banana Pro, Veo, Sora,
// Runway, composition). Assets are generated by Claude via the
// creative_* MCP tools and registered here; this module is the
// review/status layer the CRM renders — it does not call generation
// APIs itself (no provider key is exposed to the client bundle).

export const TEASER_PROJECT = {
  id: 'updraft',
  title: 'UPDRAFT',
  logline:
    'A getaway driver and his last accomplice run out of road on a mountain pass — and take the only way out left: straight off the cliff.',
  flow_id: 'fCoaIhUMPVGmMRrBWjOe',
  flow_url: 'https://elevenlabs.io/app/flows/fCoaIhUMPVGmMRrBWjOe',
}

// status: 'ready' | 'pending' | 'blocked'
export const ANCHORS = [
  {
    id: 'marcus',
    name: 'Marcus',
    description: 'Black man, early 50s, short greying hair, thin-framed glasses — the wheelman.',
    shots: [
      { id: 'marcus-face',  label: 'Face',  status: 'ready',   src: '/creator-studio/anchors/marcus-face.png' },
      { id: 'marcus-front', label: 'Front', status: 'pending', src: null },
      { id: 'marcus-back',  label: 'Back',  status: 'pending', src: null },
    ],
  },
  {
    id: 'simone',
    name: 'Simone',
    description: 'Black woman, early 40s, long dark curly hair — the last accomplice.',
    shots: [
      { id: 'simone-face',  label: 'Face',  status: 'ready',   src: '/creator-studio/anchors/simone-face.png' },
      { id: 'simone-front', label: 'Front', status: 'pending', src: null },
      { id: 'simone-back',  label: 'Back',  status: 'pending', src: null },
    ],
  },
]

export const LOCATIONS = [
  {
    id: 'adirondack-ridge-road',
    name: 'Adirondack Ridge Road',
    description: 'Two-lane mountain pass through dense pine forest — the chase corridor.',
    status: 'ready',
    src: '/creator-studio/locations/adirondack-ridge-road.png',
  },
  {
    id: 'cliff-top-overlook',
    name: 'Cliff-Top Overlook',
    description: 'Dead-end overlook above the canyon — where the chase ends and the climax begins.',
    status: 'ready',
    src: 'https://cdn.gamma.app/n8e5peu5ixl5398/design-anything/extXhUvtSsiV1MSH6FFEa/hdXinXXZ3yVABqkD5ukFn.jpg',
    hosted: 'gamma',
  },
]

export const VEHICLES = [
  {
    id: 'audi-rs8',
    name: 'Audi RS8 (hero car)',
    description: 'Matte black, blacked-out trim — Marcus’s car.',
    status: 'ready',
    src: 'https://cdn.gamma.app/n8e5peu5ixl5398/design-anything/9jQ1Y1SFdgr1liv55YM9B/2CBoCN1WL3XZS7YtcOggR.jpg',
    hosted: 'gamma',
  },
  {
    id: 'state-police-cruiser',
    name: 'State Police Cruiser',
    description: 'Black-and-white cruiser with roof light bar — the pursuit.',
    status: 'ready',
    src: 'https://cdn.gamma.app/n8e5peu5ixl5398/design-anything/XWC9XUFQlmyqNAQcAAr1W/do8rb2YL876i05IqJfpbj.jpg',
    hosted: 'gamma',
  },
  {
    id: 'hang-glider-pair',
    name: 'Hang Glider Pair',
    description: 'Red/orange and blue sails — the escape off the cliff.',
    status: 'ready',
    src: 'https://cdn.gamma.app/n8e5peu5ixl5398/design-anything/cSqZwZ2PgBApfNRku5c1g/NvRJ8Xzqgu-gJrqy10OIq.jpg',
    hosted: 'gamma',
  },
]

// Shot list for the teaser cut — each beat names the anchors/
// locations/vehicles it depends on, so the studio can show what's
// blocking a given shot from being generated.
export const SHOT_LIST = [
  { id: 'shot-01', beat: 'Cold open — RS8 screams down the ridge road, cruiser lights in the mirror.', needs: ['audi-rs8', 'state-police-cruiser', 'adirondack-ridge-road'] },
  { id: 'shot-02', beat: 'Marcus, knuckles white on the wheel — road noise, no dialogue.', needs: ['marcus', 'audi-rs8', 'adirondack-ridge-road'] },
  { id: 'shot-03', beat: 'Simone unclips two hang gliders from the trunk as the road runs out.', needs: ['simone', 'hang-glider-pair', 'cliff-top-overlook'] },
  { id: 'shot-04', beat: 'The RS8 abandoned, doors open, at the cliff edge — cruisers converging.', needs: ['audi-rs8', 'state-police-cruiser', 'cliff-top-overlook'] },
  { id: 'shot-05', beat: 'Two gliders launch off the overlook into open air. Title card: UPDRAFT.', needs: ['marcus', 'simone', 'hang-glider-pair', 'cliff-top-overlook'] },
]

export function anchorStatus(anchor) {
  const statuses = anchor.shots.map(s => s.status)
  if (statuses.every(s => s === 'ready')) return 'ready'
  if (statuses.some(s => s === 'ready')) return 'pending'
  return 'blocked'
}

function statusOf(assetId) {
  const anchor = ANCHORS.find(a => a.id === assetId)
  if (anchor) return anchorStatus(anchor)
  const found = [...LOCATIONS, ...VEHICLES].find(a => a.id === assetId)
  return found?.status ?? 'blocked'
}

export function shotReadiness(shot) {
  const statuses = shot.needs.map(statusOf)
  if (statuses.every(s => s === 'ready')) return 'ready'
  if (statuses.some(s => s === 'blocked')) return 'blocked'
  return 'pending'
}

export function projectSummary() {
  const allAssets = [
    ...ANCHORS.flatMap(a => a.shots.map(s => ({ ...s, kind: 'anchor', parent: a.name }))),
    ...LOCATIONS.map(l => ({ ...l, kind: 'location' })),
    ...VEHICLES.map(v => ({ ...v, kind: 'vehicle' })),
  ]
  const ready = allAssets.filter(a => a.status === 'ready').length
  return { total: allAssets.length, ready, pending: allAssets.length - ready }
}
