import { useEffect, useState } from 'react'
import { supabase } from '../../lib/supabase.js'
import { fromModuleSchema } from '../../lib/morpheus.js'
import { cachedRoute, cacheRoute, enqueue, flush, pending } from './fieldOffline.js'

const NEXT={DISPATCHED:'ACCEPTED',ACCEPTED:'EN_ROUTE',EN_ROUTE:'ARRIVED',ARRIVED:'IN_PROGRESS',IN_PROGRESS:'COMPLETED'}
const LABEL={ACCEPTED:'ACCEPT JOB',EN_ROUTE:'EN ROUTE',ARRIVED:'ARRIVED',IN_PROGRESS:'START COLLECTION',COMPLETED:'COMPLETE STOP'}
async function send(item){const fn=item.type==='transition'?'melrah_field_transition':'melrah_field_record_collection';const {error}=await supabase.rpc(fn,item.payload);if(error)throw error}

export default function FieldMobile(){
 const [rows,setRows]=useState(cachedRoute()),[active,setActive]=useState(null),[online,setOnline]=useState(navigator.onLine),[queued,setQueued]=useState(pending().length),[msg,setMsg]=useState(''),[collect,setCollect]=useState({code:'',fill:'',weight:'',count:'',contamination:'0',bag:'',notes:'',before:'',after:''})
 async function load(){const r=await fromModuleSchema('melrah','service_appointment',q=>q.order('scheduled_start',{ascending:true}).limit(50));if(!r.error){setRows(r.data);cacheRoute(r.data);setActive(r.data.find(x=>!['COMPLETED','CANCELLED'].includes(x.status))||r.data[0]||null)}else{const c=cachedRoute();setActive(c.find(x=>!['COMPLETED','CANCELLED'].includes(x.status))||c[0]||null)}}
 useEffect(()=>{load()},[])
 useEffect(()=>{const on=async()=>{setOnline(true);setQueued(await flush(send));load()},off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[])
 async function step(){const status=NEXT[active?.status];if(!status)return;const item={type:'transition',payload:{p_appointment_id:active.id,p_status:status}};try{if(!online)throw Error();await send(item);setMsg(LABEL[status]+' saved')}catch{setQueued(enqueue(item));setMsg('Saved offline — automatic sync queued')}setActive({...active,status})}
 async function saveCollection(e){e.preventDefault();if(!active||!collect.code||!collect.bag){setMsg('Container code and bag ID are required.');return}let pos={};try{pos=await new Promise((ok,no)=>navigator.geolocation.getCurrentPosition(p=>ok({lat:p.coords.latitude,lng:p.coords.longitude}),no,{timeout:5000}))}catch{}const item={type:'collection',payload:{p_appointment_id:active.id,p_container_code:collect.code,p_weight_lbs:collect.weight?Number(collect.weight):null,p_package_count:collect.count?Number(collect.count):null,p_contamination_pct:Number(collect.contamination||0),p_fill_level_pct:collect.fill?Number(collect.fill):null,p_bag_batch_id:collect.bag,p_notes:collect.notes||null,p_latitude:pos.lat||null,p_longitude:pos.lng||null,p_before_photo_path:collect.before||null,p_after_photo_path:collect.after||null}};try{if(!online)throw Error();await send(item);setMsg('Collection record saved.')}catch{setQueued(enqueue(item));setMsg('Collection saved offline — automatic sync queued.')}setCollect({...collect,weight:'',count:'',fill:'',bag:'',notes:'',before:'',after:''})}\n function navigate(){if(!active)return;const q=encodeURIComponent(active.route_name||'Collection stop');window.open('https://www.google.com/maps/search/?api=1&query='+q,'_blank','noopener,noreferrer')}\n async function scan(){if(!('BarcodeDetector' in window)){setMsg('Camera QR scanning is not supported on this browser. Enter the container code manually.');return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});setMsg('Camera ready. Point at the container QR code.');const video=document.createElement('video');video.srcObject=stream;video.setAttribute('playsinline','');await video.play();const detector=new BarcodeDetector({formats:['qr_code']});let value='';for(let i=0;i<30&&!value;i++){const codes=await detector.detect(video);value=codes[0]?.rawValue||'';if(!value)await new Promise(r=>setTimeout(r,150))}stream.getTracks().forEach(t=>t.stop());if(value){setCollect({...collect,code:value});setMsg('Scanned '+value)}else setMsg('No QR detected. Enter the code manually.')}catch{setMsg('Camera unavailable. Enter the container code manually.')}}\n const next=NEXT[active?.status]
 return <main className='field-mobile'>
  <header><div><small>MELRAH FIELD™</small><h2>Today’s Route</h2></div><b className={online?'field-online':'field-offline'}>{online?'ONLINE':'OFFLINE'} · {queued} QUEUED</b></header>
  {!active?<section className='field-card'>No assigned stops. {rows.length?'Route complete.':'Connect once to download the Route Briefcase.'}</section>:<>
   <section className='field-card'><small>NEXT STOP</small><h1>{active.route_name||'Collection Route'}</h1><p>{active.scheduled_start?new Date(active.scheduled_start).toLocaleString():'Unscheduled'} · Stop {active.sequence_no||'—'}</p><strong>{active.status.replace('_',' ')}</strong></section>
   <section className='field-card'><small>GUIDED WORKFLOW</small><p className='field-help'>One action at a time. Morpheus timestamps each step and keeps it in your Route Briefcase if service drops.</p>{next&&<button className='field-primary' onClick={step}>{LABEL[next]}</button>}</section>
   {['ARRIVED','IN_PROGRESS'].includes(active.status)&&<form className='field-card' onSubmit={saveCollection}><small>SCAN + COLLECT</small><button type='button' className='field-secondary' onClick={scan}>SCAN CONTAINER QR</button><label>Container code<input value={collect.code} onChange={e=>setCollect({...collect,code:e.target.value})} placeholder='MEL-ALB-003-FP-01'/></label><div className='field-form-grid'><label>Fill %<input inputMode='decimal' value={collect.fill} onChange={e=>setCollect({...collect,fill:e.target.value})}/></label><label>Weight lb<input inputMode='decimal' value={collect.weight} onChange={e=>setCollect({...collect,weight:e.target.value})}/></label><label>Package count<input inputMode='numeric' value={collect.count} onChange={e=>setCollect({...collect,count:e.target.value})}/></label><label>Contamination %<input inputMode='decimal' value={collect.contamination} onChange={e=>setCollect({...collect,contamination:e.target.value})}/></label></div><label>Bag / batch ID<input value={collect.bag} onChange={e=>setCollect({...collect,bag:e.target.value})} placeholder='FP-0920-003'/></label><label>Before photo<input type='file' accept='image/*' capture='environment' onChange={e=>setCollect({...collect,before:e.target.files?.[0]?.name||''})}/></label><label>After photo<input type='file' accept='image/*' capture='environment' onChange={e=>setCollect({...collect,after:e.target.files?.[0]?.name||''})}/></label><label>Notes<textarea value={collect.notes} onChange={e=>setCollect({...collect,notes:e.target.value})}/></label><button className='field-primary'>SAVE COLLECTION</button></form>}
   {msg&&<div className='field-message' role='status'>{msg}</div>}
  </>}
  <nav className='field-tabs'><button>TODAY</button><button onClick={navigate}>MAP</button><button onClick={scan}>SCAN</button><button onClick={async()=>setQueued(await flush(send))}>SYNC</button></nav>
 </main>
}